development:
      host: localhost
      adapter: mysql
      database: fed
      port: 3306
      username: root
      password: 

test: &test
      host: localhost
      adapter: mysql
      database: test
      port: 3306
      username: test
      password: test

production:
      host: localhost
      adapter: mysql
      database: testimonydb
      port: 3306
      username: testimony
      password: testimony2017
cucumber:
  <<: *test
